version: '3'

services:
  food_recipe:
    build: .
    container_name: recipe
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped
    environment:
      DB_NAME: food_recipe_db
      DB_USER: ibodullo
      DB_PASS: qwer1234#
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_recipe_db
      POSTGRES_USER: ibodullo
      POSTGRES_PASSWORD: qwer1234#

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

  celery:
    build: .
    command: celery -A food_recipe worker -l INFO
    restart: unless-stopped
    depends_on:
      - food_recipe
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: food_recipe.settings
      DB_NAME: food_recipe_db
      DB_USER: ibodullo
      DB_PASS: qwer1234#
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379


  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8080:80"
    depends_on:
      - food_recipe

volumes:
  pgdata:
  static_data:
  media_data:
